#!/usr/bin/env julia

using Fire
using RedisAlchemy

@main function main(keys...; db::Int=0, all::Bool=false)
    conn = RedisConnection(db=db)

    if all
        exec(conn, "flushdb")
        println("all clear")
    else
        n = mapreduce(+, 0, keys) do key
            exec(conn, "del", key)
        end
        println("deleted $n key(s)")
    end
end
